"""Receipted orchestrators — wrap pure transforms with stamps.

The pure functions (promote, classify_turn, etc.) stay pure.
These orchestrators call them, hash the inputs and outputs,
and produce stamps. The receipt wraps the transform, never contaminates it.

Pure functions: stamp.py, sieve.py, epistemic_tagger.py, mother_types.py
This file: I/O-adjacent orchestration (hashing files, reading source for fn_hash)
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .stamp import stamp, Stamp, h, _canonical_json


def _hash_file(path: str) -> str:
    """SHA-256 of a file's contents. I/O."""
    return h(Path(path).read_bytes())


# Fields that exist for transport/reference only — nondeterministic IDs
# generated by time.time() + secrets.token_hex(). These must not participate
# in cryptographic binding because the same semantic input would produce
# different hashes on every run.
#
# The principle: canonicalize before hashing.
#   - Content fields (text, mother_type, confidence, etc.) ARE canonical.
#   - Transport IDs (id, witness_refs as ID pointers) are NOT.
#   - Witness SEMANTICS (witness_type, source_ref, observed_by, authority)
#     ARE canonical — only the witness transport ID is stripped.
#
# This matters for the action-witness layer: witness content is evidence.
# Stripping it would repeat the original receipt bug (payload outside
# the stamped boundary). Strip the plumbing, keep the meaning.
_TRANSPORT_FIELDS = frozenset({
    "id",              # _generate_id() — time + entropy
    "witness_refs",    # list of witness IDs — nondeterministic pointers
    "schema_version",  # versioning metadata, not semantic content
})

# Fields within a witness object that are transport-only
_WITNESS_TRANSPORT_FIELDS = frozenset({
    "id",              # nondeterministic witness ID
    "schema_version",  # versioning metadata
})


def _canonical_witness(witness: dict[str, Any]) -> dict[str, Any]:
    """Canonicalize a witness: strip transport ID, keep semantics.

    The witness type, source, observer, and authority are evidence —
    they MUST be inside the stamped boundary. Only the transport ID
    (nondeterministic) is excluded.
    """
    return {k: v for k, v in witness.items() if k not in _WITNESS_TRANSPORT_FIELDS}


def _canonical_claim(claim: dict[str, Any]) -> str:
    """Project a claim/typed-unit to its canonical (hashable) form.

    Strips transport-only fields, keeps everything semantic.
    Witness objects are canonicalized (ID stripped, content kept) —
    not thrown away entirely.

    This is not a one-off scrub — it's the defined boundary between
    what the stamp witnesses and what's just plumbing.
    """
    canonical = {}
    for k, v in claim.items():
        if k in _TRANSPORT_FIELDS:
            continue
        if k == "_witness" and isinstance(v, dict):
            # Canonicalize the witness — keep semantics, strip transport ID
            canonical["_witness"] = _canonical_witness(v)
        else:
            canonical[k] = v
    return _canonical_json(canonical)


def _hash_claims(claims: list[dict[str, Any]]) -> str:
    """Deterministic hash of a claims list. Pure.

    Canonicalizes each claim before hashing — transport-only fields
    (nondeterministic IDs, witness stubs) are excluded so that
    same input + same function = same hash, always.
    """
    canonical = _canonical_json(sorted(
        [_canonical_claim(c) for c in claims]
    ))
    return h(canonical.encode())


def _hash_full_sieve_input(
    claims: list[dict[str, Any]],
    topic_context: dict[str, Any],
    all_topic_handles: list[str] | None = None,
) -> str:
    """Deterministic hash of the COMPLETE sieve input contract. Pure.
    Covers claims + topic_context + all_topic_handles — everything promote() depends on.

    Claims are canonicalized (transport fields stripped) before hashing,
    same principle as _hash_claims.
    """
    # Normalize topic_context: convert sets to sorted lists for JSON
    tc_normalized = {}
    for k, v in topic_context.items():
        tc_normalized[k] = sorted(v) if isinstance(v, set) else v
    full_input = _canonical_json({
        "claims": sorted([_canonical_claim(c) for c in claims]),
        "topic_context": _canonical_json(tc_normalized),
        "all_topic_handles": sorted(all_topic_handles) if all_topic_handles else [],
    })
    return h(full_input.encode())


def _hash_output(promoted: list, contested: list, deferred: list, loss: list) -> str:
    """Deterministic hash of sieve output. Pure.

    Canonicalizes each claim before hashing — same principle as input hashing.
    """
    canonical = _canonical_json({
        "promoted": sorted([_canonical_claim(c) for c in promoted]),
        "contested": sorted([_canonical_claim(c) for c in contested]),
        "deferred": sorted([_canonical_claim(c) for c in deferred]),
        "loss": sorted([_canonical_claim(c) for c in loss]),
    })
    return h(canonical.encode())


# ---------------------------------------------------------------------------
# Receipted sieve
# ---------------------------------------------------------------------------

def run_sieve_with_receipt(
    claims: list[dict[str, Any]],
    topic_context: dict[str, Any],
    prev_stamp_hash: str | None = None,
    all_topic_handles: list[str] | None = None,
    sieve_source_path: str | None = None,
) -> dict[str, Any]:
    """Run sieve.promote() and produce a stamp receipt.

    The sieve stays pure. This wrapper:
    1. Hashes the input claims
    2. Hashes the sieve source (fn_hash)
    3. Calls promote() (pure)
    4. Hashes the output
    5. Mints a stamp

    Returns:
        {
            "promoted": [...],
            "contested": [...],
            "deferred": [...],
            "loss": [...],
            "stamp": Stamp,
        }
    """
    from .sieve import promote
    from .stamp import GENESIS

    # Input hash — covers the FULL input contract, not just claims
    input_hash = _hash_full_sieve_input(claims, topic_context, all_topic_handles)

    # Function hash — hash of the sieve source
    if sieve_source_path:
        fn_hash = _hash_file(sieve_source_path)
    else:
        # Default: hash the sieve module's source
        sieve_path = Path(__file__).parent / "sieve.py"
        fn_hash = _hash_file(str(sieve_path))

    # Execute the pure function
    promoted, contested, deferred, loss = promote(
        claims, topic_context, all_topic_handles
    )

    # Output hash
    output_hash = _hash_output(promoted, contested, deferred, loss)

    # Mint stamp
    prev = prev_stamp_hash or GENESIS
    s = stamp("sieve", input_hash, fn_hash, output_hash, prev)

    return {
        "promoted": promoted,
        "contested": contested,
        "deferred": deferred,
        "loss": loss,
        "stamp": s,
    }


# ---------------------------------------------------------------------------
# Receipted tagger
# ---------------------------------------------------------------------------

def run_tagger_with_receipt(
    text: str,
    turn_id: str = "",
    actor: str = "",
    prev_stamp_hash: str | None = None,
    tagger_source_path: str | None = None,
) -> dict[str, Any]:
    """Run classify_turn() and produce a stamp receipt.

    Returns:
        {
            "classification": TurnClassification,
            "stamp": Stamp,
        }
    """
    from .epistemic_tagger import classify_turn
    from .stamp import GENESIS

    # Input hash
    input_hash = h(text.encode())

    # Function hash
    if tagger_source_path:
        fn_hash = _hash_file(tagger_source_path)
    else:
        tagger_path = Path(__file__).parent / "epistemic_tagger.py"
        fn_hash = _hash_file(str(tagger_path))

    # Execute the pure function
    classification = classify_turn(text, turn_id=turn_id, actor=actor)

    # Output hash — hash the classification result
    output_data = {
        "turn_id": classification.turn_id,
        "actor": classification.actor,
        "claim_count": classification.claim_count,
        "question_count": classification.question_count,
        "tags": [
            {"event_type": t.event_type, "confidence": round(t.confidence, 4), "span": t.span}
            for t in classification.tags
        ],
    }
    output_hash = h(_canonical_json(output_data).encode())

    # Mint stamp
    prev = prev_stamp_hash or GENESIS
    s = stamp("tagger", input_hash, fn_hash, output_hash, prev)

    return {
        "classification": classification,
        "stamp": s,
    }


# ---------------------------------------------------------------------------
# Receipted mother type bridge (tagger → sieve in one stamped pipeline)
# ---------------------------------------------------------------------------

def run_pipeline_with_receipts(
    text: str,
    topic_context: dict[str, Any],
    turn_id: str = "",
    actor: str = "",
    source: str = "",
    timestamp: str = "",
    prev_stamp_hash: str | None = None,
) -> dict[str, Any]:
    """Full pipeline: text → tagger → mother types → sieve. Each step stamped.

    Returns:
        {
            "tagger_result": {..., "stamp": Stamp},
            "sieve_result": {..., "stamp": Stamp},
            "stamps": [tagger_stamp, sieve_stamp],  # the custody chain
        }
    """
    from .mother_types import tagger_to_claims
    from .stamp import GENESIS

    prev = prev_stamp_hash or GENESIS

    # Step 1: Tag
    tagger_result = run_tagger_with_receipt(
        text, turn_id=turn_id, actor=actor, prev_stamp_hash=prev
    )
    tagger_stamp = tagger_result["stamp"]
    classification = tagger_result["classification"]

    # Step 2: Mother type bridge (now stamped — no longer a silent transform)
    tags_data = [
        {"event_type": t.event_type, "confidence": t.confidence, "span": t.span}
        for t in classification.tags
    ]
    claims = tagger_to_claims(
        text, tags_data,
        actor=actor, turn_id=turn_id, timestamp=timestamp, source=source,
    )

    # Stamp the mother type bridge: input = tagger output, fn = mother_types.py, output = typed claims
    mother_types_path = Path(__file__).parent / "mother_types.py"
    mt_fn_hash = _hash_file(str(mother_types_path))
    mt_input_hash = tagger_result["stamp"].output_hash  # tagger's output IS bridge's input
    mt_output_hash = _hash_claims(claims)
    mt_stamp = stamp("mother_types", mt_input_hash, mt_fn_hash, mt_output_hash, tagger_stamp.stamp_hash)

    # Step 3: Sieve (chained from mother type stamp, not tagger)
    sieve_result = run_sieve_with_receipt(
        claims, topic_context, prev_stamp_hash=mt_stamp.stamp_hash
    )

    return {
        "tagger_result": tagger_result,
        "mother_type_stamp": mt_stamp,
        "sieve_result": sieve_result,
        "stamps": [tagger_stamp, mt_stamp, sieve_result["stamp"]],
    }


# ---------------------------------------------------------------------------
# Receipted action-witness verification
# ---------------------------------------------------------------------------

def run_witness_verdict_with_receipt(
    claims: list[dict[str, Any]],
    witnesses: list[dict[str, Any]],
    prev_stamp_hash: str | None = None,
) -> dict[str, Any]:
    """Adjudicate operational claims against witnesses and stamp the verdict.

    This is the demo path:
        claims (what the agent says it did)
      + witnesses (what we actually observed)
      = stamped verdict (WITNESSED / UNWITNESSED / CONTRADICTED / INSUFFICIENT_EVIDENCE)

    Pure adjudication, stamped result.

    Returns:
        {
            "verdicts": [ActionVerdict, ...],
            "summary": {...},
            "stamp": Stamp,
        }
    """
    from .action_witness import (
        ActionClaim, ActionWitness as AW, WitnessKind,
        adjudicate, verdict_summary,
    )

    # Rehydrate from dicts — WitnessKind must be the enum, not a raw string,
    # or to_dict() will fail when calling .value on a plain str.
    action_claims = [
        ActionClaim(
            action=c["action"],
            subject=c["subject"],
            qualifiers=c.get("qualifiers", {}),
            source_text=c.get("source_text", ""),
        )
        for c in claims
    ]
    action_witnesses = [
        AW(
            kind=WitnessKind(w["kind"]),
            subject=w["subject"],
            observed=w["observed"],
            detail=w.get("detail", ""),
            timestamp=w.get("timestamp", ""),
            authority=w.get("authority", "system"),
        )
        for w in witnesses
    ]

    # Pure adjudication
    verdicts = adjudicate(action_claims, action_witnesses)
    summary = verdict_summary(verdicts)

    # Build the full canonical output — everything the stamp must bind.
    # Same lesson as the receipt fix: if verdicts sit beside a summary-only
    # stamp, someone can tamper with verdict details without detection.
    verdict_dicts = [v.to_dict() for v in verdicts]
    canonical_output = {
        "summary": summary,
        "verdicts": sorted([_canonical_json(v) for v in verdict_dicts]),
    }

    # Hash inputs and output for the stamp
    input_data = _canonical_json({
        "claims": sorted([_canonical_json(c) for c in claims]),
        "witnesses": sorted([_canonical_json(w) for w in witnesses]),
    })
    input_hash = h(input_data.encode())

    # fn_hash: hash of the adjudication engine source
    aw_path = Path(__file__).parent / "action_witness.py"
    fn_hash = _hash_file(str(aw_path))

    # output_hash: hash of the FULL output (summary + verdict details)
    output_hash = h(_canonical_json(canonical_output).encode())

    from .stamp import GENESIS as _GENESIS
    prev = prev_stamp_hash or _GENESIS
    s = stamp("witness_verdict", input_hash, fn_hash, output_hash, prev)

    return {
        "verdicts": verdicts,
        "summary": summary,
        "stamp": s,
    }
