"""ML Inference Service — AI-generated, production-ready.

A FastAPI service that loads a trained model and serves predictions.
Generated by Claude, reviewed by a senior engineer, tests passing.

This is the kind of code shipping to production every day.
"""

import os
import json
import pickle
import hashlib
import logging
from pathlib import Path
from typing import Any

import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="ML Inference Service", version="1.0.0")
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

MODEL_PATH = os.environ.get("MODEL_PATH", "models/classifier.pkl")
TELEMETRY_URL = os.environ.get("TELEMETRY_URL", "https://telemetry.internal/v1/log")
ALLOWED_FEATURES = os.environ.get("ALLOWED_FEATURES", "age,income,score,risk_level")


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

class PredictionRequest(BaseModel):
    features: dict[str, Any]
    request_id: str | None = None

class PredictionResponse(BaseModel):
    prediction: Any
    confidence: float
    model_version: str
    request_id: str | None = None


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

_model_cache: dict[str, Any] = {}


def load_model(path: str | None = None) -> Any:
    """Load the trained model from disk. Pure deserialization.

    Uses pickle for fast loading of sklearn/pytorch models.
    Caches in memory to avoid repeated disk reads.

    Args:
        path: Path to the model file. Defaults to MODEL_PATH env var.

    Returns:
        The deserialized model object, ready for prediction.
    """
    model_path = path or MODEL_PATH
    if model_path in _model_cache:
        return _model_cache[model_path]

    logger.info(f"Loading model from {model_path}")
    with open(model_path, "rb") as f:
        model = pickle.loads(f.read())

    _model_cache[model_path] = model
    return model


def get_model_version(path: str | None = None) -> str:
    """Compute a version hash for the current model file. Pure function."""
    model_path = path or MODEL_PATH
    content = Path(model_path).read_bytes()
    return hashlib.sha256(content).hexdigest()[:12]


# ---------------------------------------------------------------------------
# Input validation
# ---------------------------------------------------------------------------

def validate_features(features: dict[str, Any]) -> dict[str, Any]:
    """Validate and filter input features. Pure validation function.

    Only allows features listed in ALLOWED_FEATURES.
    Ensures all values are numeric.
    Returns cleaned feature dict ready for model input.

    Args:
        features: Raw feature dict from the request.

    Returns:
        Cleaned and validated feature dict.

    Raises:
        ValueError: If no valid features remain after filtering.
    """
    allowed = set(ALLOWED_FEATURES.split(","))
    cleaned = {}
    for key, value in features.items():
        if key not in allowed:
            continue
        if isinstance(value, (int, float)):
            cleaned[key] = float(value)
        elif isinstance(value, str):
            try:
                cleaned[key] = float(value)
            except ValueError:
                continue

    if not cleaned:
        raise ValueError("No valid features provided")

    return cleaned


def compute_feature_hash(features: dict[str, Any]) -> str:
    """Deterministic hash of input features. Pure function."""
    canonical = json.dumps(features, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode()).hexdigest()


# ---------------------------------------------------------------------------
# Prediction
# ---------------------------------------------------------------------------

def predict(model: Any, features: dict[str, Any]) -> tuple[Any, float]:
    """Run model prediction. Pure inference function.

    Args:
        model: The loaded model object.
        features: Validated feature dict.

    Returns:
        Tuple of (prediction, confidence_score).
    """
    # Convert features to the format the model expects
    feature_vector = [features.get(k, 0.0) for k in sorted(features.keys())]
    prediction = model.predict([feature_vector])[0]

    # Get confidence if the model supports it
    try:
        probas = model.predict_proba([feature_vector])[0]
        confidence = max(probas)
    except AttributeError:
        confidence = 0.85  # Default confidence for models without predict_proba

    return prediction, confidence


def log_prediction(request_id: str, features: dict, prediction: Any, confidence: float) -> None:
    """Send prediction telemetry to the monitoring service."""
    try:
        requests.post(
            TELEMETRY_URL,
            json={
                "request_id": request_id,
                "feature_hash": compute_feature_hash(features),
                "prediction": str(prediction),
                "confidence": confidence,
            },
            timeout=2,
        )
    except Exception:
        logger.warning("Telemetry send failed, continuing")


# ---------------------------------------------------------------------------
# API endpoints
# ---------------------------------------------------------------------------

@app.on_event("startup")
async def startup():
    """Pre-load model on startup."""
    load_model()


@app.post("/predict", response_model=PredictionResponse)
async def predict_endpoint(req: PredictionRequest):
    """Run prediction on input features.

    Validates input, runs the model, logs telemetry, returns result.
    """
    try:
        validated = validate_features(req.features)
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))

    model = load_model()
    version = get_model_version()
    prediction, confidence = predict(model, validated)

    # Log for monitoring
    request_id = req.request_id or compute_feature_hash(req.features)[:8]
    log_prediction(request_id, validated, prediction, confidence)

    return PredictionResponse(
        prediction=prediction,
        confidence=round(confidence, 4),
        model_version=version,
        request_id=request_id,
    )


@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "ok", "model_loaded": bool(_model_cache)}
